### ISSUE TITLE
Parsing classes with imports

### ISSUE THREAD

**Issue by d9k** [xddq/ts2typebox#25]
Seems `ts2typebox` can't parse `class` and doesn't process imports

```ts
import { Column, DataType, Default, Model, Table } from 'sequelize-typescript';

@Table
export class CarBrand extends Model<CarBrand> {
  @Column
  name: string;

  @Default(true)
  @Column(DataType.BOOLEAN)
  isCertified: boolean;

  @Column
  imgUrl: string;

  @Column
  orderNo: number;

  @Column
  carsCount: number;
}
```

(example from [sequelize-typescript-migration-lts/README](https://github.com/mmRoshani/sequelize-typescript-migration/blob/master/README.md#usage-example))

```
> ts2typebox -i carBrand.ts --output-stdout
Unhandled: ImportDeclaration import { Column, DataType, Default, Model, Table } from 'sequelize-typescript';
/**
 * ATTENTION. This code was AUTO GENERATED by ts2typebox. While I don't know
 * your use case, there is a high chance that direct changes to this file get
 * lost. Consider making changes to the underlying Typescript code you use to
 * generate this file instead. The default file is called "types.ts", perhaps
 * have a look there! :]
 */
```

It would be very nice to be able to create skeleton of TypeBox validators from database models code.

**Comment by xddq** [comment]
hey @d9k !

Sounds like a handy use case. However, this package is nowadays just a simple wrapper around https://github.com/sinclairzx81/typebox-codegen . I think you should mention the issue there. Once it is fixed updating the dependencies here is no problem.

Will probably close this in a couple of weeks in case there is no response.

**Comment by d9k** [comment]
@xddq, thanks for the answer, I opened an [issue at typebox-codegen](https://github.com/sinclairzx81/typebox-codegen/issues/33) too.

**Comment by xddq** [comment]
closing, for more info see the mentioned issue at typebox-codegen
